### ISSUE TITLE
[Curious] QUnit 0.2.x deprecate global asserts

### ISSUE THREAD

**Issue by taddeimania** [toranb/ember-cli-test-helpers#1]
There have been a number of changes in ember-cli to get it to QUnit 0.2.x compatible and one of those deprecations is to pass the body of the test function an "assert" argument to call .equal() or .ok() off of.

Just curious of your thoughts on the structure of these test helpers when the asserts aren't available to the function as a global.

See this random blueprint for an example of what I mean:

https://github.com/ember-cli/ember-cli/blob/master/blueprints/controller-test/files/tests/unit/__path__/__test__.js

**Comment by williamsbdev** [comment]
@taddeimania I'm assuming that we will just change the API for each of the helpers to take "assert" as the first argument to the function.

**Comment by taddeimania** [comment]
That's what we've landed on for the time being.  Let me know if you guys come up with a better solution :+1:

**Comment by williamsbdev** [comment]
I just submitted a PR tonight for test coverage around each helper. Once that gets merge, I'll work on adding the assert argument to each helper.

**Comment by toranb** [comment]
I was wondering if we could (instead) just import assert from qunit or ember-qunit (I'd hate to make each helper take another argument) -not sure if this will work/should work/could work

**Comment by taddeimania** [comment]
Perhaps in the helper definition you bound assert to the function, that way when you actually called the helper from the test it would work something like this?

```javascript
var assert = {equal: function(a, b){return a == b;}};

var testHelperAssertEqual = function(a, b) {
  console.log(assert.equal(a, b));
}.bind(assert)

testHelperAssertEqual(1, 2);
```

**Comment by taddeimania** [comment]
Yeah I just tried all of this in a real ember test and that's not going to work.  This has piqued my interest - and now I wont get any sleep tonight.

**Comment by taddeimania** [comment]
Okay here's a temporary workaround I guess.

You could add
```javascript
/* globals QUnit */
```
to your test helpers file

and inside of your test helper instead of having
``` javascript
  ok(value);
```
You'd have
``` javascript
  QUnit.assert.ok(value);
```
again, it's not the best thing but it will get the asserts working for the helpers.

**Comment by taddeimania** [comment]
re: toran, if you're going to go to a global route - you should probably just import assert rather than depending on the QUnit global.

**Comment by williamsbdev** [comment]
@taddeimania Where were you importing assert from? From ember-qunit (I didn't see it in here) or from QUnit? I really like the idea of just importing it.

Thanks!

**Comment by taddeimania** [comment]
It's not in ember-qunit but it's in qunit.

```javascript
import assert from 'qunit';
```
