### ISSUE TITLE
[BUG] Visit is not defined with module wrapper

### ISSUE THREAD

**Issue by williamsbdev** [toranb/ember-cli-test-helpers#15]
I ran into this issue when I was upgrading my projects. I swapped out the `module` from `qunit` with the `module` wrapper defined in this addon. This addon is expecting the `beforeEach` and `afterEach` function to be defined to properly configure the test with `injectTestHelpers` and `setupForTesting` which is done inside the `start-app`.

When I was upgrading an old ember-cli app, I had generated the acceptance tests when the `beforeEach` and `afterEach` were called `setup` and `teardown`. The wrapper that ember-qunit provides will rename those functions to work with the new API of QUnit. However, the module wrapper in this addon does not do that and will break as it does not run `startApp()`. It results in a very cryptic error of `ReferenceError: visit is not defined`.

**Comment by williamsbdev** [comment]
Closing this as it is just an FYI for those upgrading that they may run into issues.

**Comment by toranb** [comment]
@williamsbdev thank you, thank you, thank you! I just ran into this upgrading from ember-cli v2.4.2 and (thankfully) your "pay it forward" comment here provided some clarity!
