### ISSUE TITLE
Cannot check a radio button that is unchecked

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-test-helpers#4]
the import of start-app fails, so the test doesn't run. There are no notifications this is happening except in running during ember-server mode.

When you fix the import, all the usage tests are failing.

**Comment by benkiefer** [comment]
It looks like a large part of the failing test problem is that you cannot import assert from qunit in the input.js file, since it is not exported by ember qunit.

https://github.com/rwjblue/ember-qunit/blob/master/lib/qunit.js

**Comment by williamsbdev** [comment]
Version 0.2.1 fixed this. We have a passing build on travis-ci now.

https://travis-ci.org/toranb/ember-cli-test-helpers

**Comment by toranb** [comment]
Awesome work @williamsbdev !!!

**Comment by benkiefer** [comment]
Thanks @williamsbdev that fixes the functionality.

The usage test is still broken on this guy. You've got a bad import which causes the test to not get run.

If you add this test to the usage test, you will see the problem because the build will not fail.

test("this should fail", function (assert) {
    assert.ok(false);
});

This line is your problem.

import startApp from "ember-cli-test-helpers/helpers/start-app";

**Comment by toranb** [comment]
That is correct - this fix is mid flight on a branch Brandon was working on and should land tonight/ tomorrow :)
