### ISSUE TITLE
[REGRESSION]: tests do not fail when overmocked

### ISSUE THREAD

**Issue by williamsbdev** [toranb/ember-cli-test-helpers#5]
When the assert was global, we were able to fail the test when there were more mocked requests than what was necessary for the test. Since the change to the assert being local to the test callback, this functionality has ceased working.

**Comment by toranb** [comment]
Just to clarify - this is the same issue we talked about in person (or is this new/something else)? If it's the same - thanks for throwing it up to clarify/and make it known! If it's something else can you show an example to help me wrap my brain around it?

**Comment by williamsbdev** [comment]
This is what we talked about in person. I just wanted to get it documented.

**Comment by williamsbdev** [comment]
I opened up this [issue](https://github.com/jquery/qunit/issues/817) to see if I can get some help from the QUnit folks on how I would accomplish this.

**Comment by williamsbdev** [comment]
We have solved this by creating our own module wrapper to fail tests in the `afterEach` function of the `QUnit.module`. Please see that PR #14 solves this.

**Comment by toranb** [comment]
Thanks for the most excellent work on this feature @williamsbdev !!! It's been on my personal hit list for some time :)
