### ISSUE TITLE
You should move the helpers to `test-support/`

### ISSUE THREAD

**Issue by bcardarella** [toranb/ember-cli-test-helpers#6]
if the helpers reside in `addon/...` that will include those helpers in all builds of `vendor.js` which will inflate the vendor footprint in environments that the test helpers shouldn't be in. Instead, you should include those helpers in `test-support/` and that will ensure they are only in `test-support.js` and thus only available in the test environment.

**Comment by toranb** [comment]
Excellent feedback! Thank you sir!

**Comment by williamsbdev** [comment]
@bcardarella Thanks for this great feedback. I'm curious though how you test these. Do you have an example addon?

**Comment by williamsbdev** [comment]
@bcardarella @toranb I found that the dockyard ember-validations has a helper in `test-support/` with some tests so I was able to copy what was done there. Thank you again for pointing out that these helpers should not live in `addon/`.

**Comment by bcardarella** [comment]
the knowledge around `test-support` isn't that wide, but I'm glad I could share!

**Comment by williamsbdev** [comment]
This recommendation has been implemented as of the 0.5.0 release.

**Comment by toranb** [comment]
Wow @williamsbdev you already got this included/versioned/published :) nice work!
